### ISSUE TITLE
Invalid event parameters when setting a reminder

### ISSUE THREAD

**Issue by AnaghSharma** [github/opensourcefriday#105] opened 2017-06-27 17:32 UTC
After signing up and clicking on Add to Calendar -> Google Calendar (under Set a reminder), getting the following error - 
![screen shot 2017-06-27 at 10 57 39 pm](https://user-images.githubusercontent.com/6823117/27601277-64e039ce-5b8c-11e7-91d0-6fc0170391ad.png)

**Comment by Tikam02** [comment] 2017-06-28 03:02
Trying to fix it.

**Comment by arun1595** [comment] 2017-06-28 19:35
The issue is with the timezone name. If you replace the timezone name(by inspecting the DOM) with `Asia/Kolkata`, it works fine.

**Comment by AnaghSharma** [comment] 2017-07-01 07:29
@arun1595 but is this the way how it is supposed to work?

**Comment by MikeMcQuaid** [comment] 2017-07-03 07:27
@AnaghSharma @Tikam02 @arun1595 Thanks for the debugging! The issue is that https://bitbucket.org/pellepim/jstimezonedetect is not creating timezone names in a format that https://addtocalendar.com can accept. I'm not sure what the best solution is, here. Any ideas?

**Comment by AnaghSharma** [comment] 2017-07-03 15:34
@MikeMcQuaid nothing as of now (still a newbie in Web Dev). I tried looking into it but could not come up with anything. Maybe others can help.

**Comment by StanleySathler** [comment] 2017-07-04 02:10
Can't we map those wrong values to the correct ones as a temporally solution?

**Comment by MikeMcQuaid** [comment] 2017-07-04 08:05
@StanleySathler Yeh, that seems like a good idea. Anyone affected by this: can you chime in with whatever timezone(s) you've been hit with these problems on?

**Comment by DavidAylaian** [comment] 2017-07-04 16:21
I don't even get invalid parameters, the website [doesn't send any data](https://i.stack.imgur.com/TuBeK.png). I tried this on multiple devices with Chrome and got the same result. I also tried Firefox and got a "secure connection failed" message. I then tried changing the timezone as @arun1595 suggested and the page just went blank.

Browsers: Google Chrome (Android), Google Chrome (Desktop), Firefox (Desktop)
Timezone: America/New York

**Comment by MikeMcQuaid** [comment] 2017-07-05 07:57
@DavidAylaian That seems to be a different issue.

**Comment by DavidAylaian** [comment] 2017-07-05 17:48
@MikeMcQuaid should I open another issue then?

**Comment by DavidAylaian** [comment] 2017-07-05 22:42
@MikeMcQuaid I'm not sure what I did, but it works now, so I won't open an issue.

**Comment by MikeMcQuaid** [comment] 2017-07-06 07:28
@DavidAylaian Thanks for letting me know 👍

**Comment by jigar1101** [comment] 2017-07-07 13:21
@MikeMcQuaid Here is a [list](https://github.com/ossfriday/ossfriday/files/1131022/timezones.json.zip) of timezones that google calendar supports along with their offsets.
A lot of them are not supported by [jstz](https://github.com/ossfriday/ossfriday/blob/master/node_modules/jstimezonedetect/dist/jstz.js)

**Comment by MikeMcQuaid** [comment] 2017-07-25 11:29
A fix for this would be to add a line below https://github.com/ossfriday/ossfriday/blob/8f58c61fc80650b72e364e217dde2a0ca20e7891/app/assets/javascripts/calendar.js#L6 which maps from the `jstz` timezone names to ones that `addtocalendar` supports. Please feel free to try and open a PR if you're interested and I can help you with things after that.

**Comment by StanleySathler** [comment] 2017-07-25 12:57
@MikeMcQuaid I can give a shot on this tonight. ;)

**Comment by master002** [comment] 2018-02-16 12:10
Hi Everyone, @StanleySathler  exactly what date format we are looking here...

**Comment by MikeMcQuaid** [comment] 2020-06-29 12:48
Closing this as no news in over two years so assuming it's no longer a problem. Shout if you disagree!

**Closed by MikeMcQuaid** 2020-06-29 12:48 UTC
Labels: help wanted
